version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
        auth:
          username: ecarlste
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t ecarlste/express-hello-world:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push ecarlste/express-hello-world:$TAG
