version: 2.1

workflows:
  continuous-delivery:
    jobs:
      - build-and-push-to-dockerhub:
          context:
            - docker-hub-creds

jobs:
  build-and-push-to-dockerhub:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run: |
          echo "DOCKER_PASSWORD=$DOCKER_PASSWORD"
          echo "DOCKER_LOGIN=$DOCKER_LOGIN"

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM

          cd express-hello-world

          docker build -t ecarlste/express-hello-world:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push ecarlste/express-hello-world:$TAG

          cd ..
